CREATE ROLE dba;
ALTER ROLE dba WITH SUPERUSER NOINHERIT NOCREATEROLE NOCREATEDB NOLOGIN REPLICATION;
CREATE ROLE gladd;
ALTER ROLE gladd WITH NOSUPERUSER INHERIT NOCREATEROLE CREATEDB LOGIN NOREPLICATION;
GRANT dba TO gladd GRANTED BY postgres
